version: '3'
services:
  app:
    image: jscardonag/devstagram:0.0.1
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    networks:
      - laravel

  postgres:
    image: 'postgres:13'
    ports:
        - '${FORWARD_DB_PORT:-5434}:5432'
    environment:
        PGPASSWORD: '${DB_PASSWORD:-secret}'
        POSTGRES_DB: '${DB_DATABASE}'
        POSTGRES_USER: '${DB_USERNAME}'
        POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
        - 'postgres:/var/lib/postgresql/data'
    networks:
        - laravel
  
networks:
  laravel:
      driver: bridge

volumes:
    postgres:
        driver: local